feat: disable peripherals
SuperFlyTV/SuperConductor pull request #92
Opened 2022-10-02 01:14 UTC by alvancamp

This PR introduces the ability to disable SuperConductor's connection to and control of peripheral devices. At a basic level there are two new settings introduced:

1. Auto-connect to all detected peripherals. This is the current behavior.
2. If auto-connect is off, peripherals can be connected to on an individual basis.

A "Panels" section has been added to the Bridges settings:
![image](https://user-images.githubusercontent.com/873012/193433781-347b1120-a9e2-4531-b3d7-a6b0ab1303ed.png)

A "+" button has been added to the top header which shows available (but disabled) peripherals. Clicking on an item in the list will make SuperConductor try to connect to it:
![image](https://user-images.githubusercontent.com/873012/193433787-2bdf640e-2c4b-4cb1-8a85-a7db7cf6a99b.png)

A "Disconnect" button has been added to the connected peripheral popover from the top header. This button has two states depending on the value of the global auto-connect setting:
![image](https://user-images.githubusercontent.com/873012/193433803-15b17844-5a4f-4d72-b906-4d802b37bbec.png)
![image](https://user-images.githubusercontent.com/873012/193433809-3ee71830-e4d1-4b1e-b9d3-8e90bc974547.png)

Closes https://github.com/SuperFlyTV/SuperConductor/issues/65

2022-10-03 02:05 UTC, alvancamp commented
I'm open to bikeshedding on how various things should be named here. I'm not convinced that I've chosen the best names for things like `AvailablePeripherals` and `clientSidePeripheralSettings`.

2022-10-16 08:11 UTC, nytamin requested changes
I'm concerned about the implementation in `PeripheralStreamDeck.Watch` and `PeripheralXkeys.Watch`.

* The OnDevice hack seems like a bad one to me.
* There is duplicated logic between the Watch-function and `AddAvailableDevice`.
* All the recently-added static properties and methods on the `Peripheral` class makes it confusing what's happening and what the responsibilities are.

**My proposal**

I think it would be better to refactor the watch-logic completely and move _all_ of the static methods in `Peripheral` into another class (`PeripheralWatcher`?) and to separate the logic of **discovering devices** and **connecting to them**.

I would implement it something like this:

* On init, `PeripheralsHandler` sets up a single instance of `PeripheralWatcher`
  * On init, `PeripheralWatcher` sets up the device-specific watches (`PeripheralStreamDeck.Watch` etc).
* The `Watch` methods should **not** connect to the devices at all, just inform `PeripheralWatcher` about their existence.
* `PeripheralWatcher` then informs `PeripheralHandler` about the available devices.
* Depending on settings, `PeripheralHandler` chooses to connect to the devices.

2022-10-16 20:25 UTC, alvancamp commented on apps/app/src/models/project/Bridge.ts
> +		autoConnectToAllPeripherals: boolean
Good catch!

2022-10-16 20:27 UTC, alvancamp commented
> I'm concerned about the implementation in `PeripheralStreamDeck.Watch` and `PeripheralXkeys.Watch`...

This is all good feedback, thanks! I believe I have implemented the changes as desired, but let me know if you still see ways things could be improved.

One thing I'm not totally happy about is the near-duplication of logic in the device-specific Watch methods (`PeripheralStreamDeck.Watch` and `PeripheralXkeys.Watch`). They're just different enough that I couldn't figure out an elegant way of making them share code. I also couldn't think of a good way to move that logic up into `PeripheralWatcher`, which might be where it belongs.

2022-10-17 05:50 UTC, alvancamp commented
I should also note that I do not have an Xkeys panel, so I am unable to test that part of this PR.

2022-10-17 17:52 UTC, nytamin approved these changes
Yes this looks much better!

I'm happy with the near-duplicated logic for xkeys and streamdeck. Since they are separate libraries and panel types, I think it's better to keep all of that logic separated.

2022-10-17 17:57 UTC, merged